### ISSUE TITLE
Parentheses around infix operations

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#139]
Currently, the default formatter turns…

```erlang
(some:thing(X) bsl (65536 * Y)) bor Z
```

…into…

```erlang
some:thing(X) bsl 65536 * Y bor Z
```

…since it _knows_ that parentheses were irrelevant there due to operator precedence.
While this is good since the semantics are preserved, sometimes the parentheses are a useful visual aid for developers. An option like `infix_parentheses => boolean()`, to always introduce parentheses when combining multiple infix operations would be nice.
I'm aware that it will probably turn…

```erlang
X + Y * Z + W
```

…into…

```erlang
(X + (Y * Z)) + W
```

…which is a bit less useful. But, as long as the default is `false`, we can just turn it on for particular modules where it really helps.

**Comment by ElFantasma** [comment]
Is there a way to tell the formatter inline settings?

Something like:
```
-fmt_preserve_parenthesis(some_function/1)
some_function(X) ->
   (some:thing(X) bsl (65536 * Y)) bor Z
```
To have the option to keep the parenthesis layout for the sake of readability when desired, instead of becoming the  module into `full parenthesis` or `no parenthesis` as a whole

**Comment by elbrujohalcon** [comment]
Not yet and I'm hesitant to introduce inter-module attributes... We do have `-format #{...}` but that's a whole-module attribute.
The kind of configuration that you propose can be implemented... But... Wouldn't that be too much?

**Comment by elbrujohalcon** [comment]
BTW... If we add inter-module config... I think it should look like this...

```erlang
-format_block #{param =>...}.
...your code...
-format_block.
```

But there too many edge cases to consider with that... If you are feel like this is needed, please open a ticket for it.

**Comment by ElFantasma** [comment]
Yeah, I agree that it may be too much. Having more "custom" syntax inside erlang code may hurt more than what it "fixes"

**Comment by ElFantasma** [comment]
But then, I would dismiss this config idea: I cannot thing a scenario where forcing the formatter to add redundant parenthesis to every expression in a module would make sense

**Comment by ElFantasma** [comment]
Maybe add some per-line magic-comment trick?

```
some_function(X) ->
   (some:thing(X) bsl (65536 * Y)) bor Z       %FMT_KEEP
```
It could be used for every other case. eg.
```
deserialize_rb(<<58,48,0,0,                                     % SERIAL_COOKIE_NO_RUNCONTAINER - FMT_KEEP
                 1,0,0,0,                                       % Size = 1                      - FMT_KEEP
                 0,0,                                           % Key = 0                       - FMT_KEEP
```

I know it's hacky and obscure but hey, I'm just throwing ideas 😬

**Comment by elbrujohalcon** [comment]
`%FMT_KEEP` is definitely a hard *no* from me. Dealing with comments is already hard at this point. I'm not willing to make it even more complex by requiring the formatter to actually parse them.
What you want to achieve should be…

```erlang
-format_block ignore.
code() -> [that,is,not,formatted].
-format_block.
```

**Comment by elbrujohalcon** [comment]
In any case, for the parentheses scenario, maybe someone has so many parenthesised/math functions that they can move them all to an individual auxiliary module where `-format #{parenthesise => all}.` makes sense. 🤷‍♂️
