### ISSUE TITLE
Format -dialyzer with name/arity

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#141]
Currently, the default formatter turns…

```erlang
-dialyzer({nowarn_function, data_encode/1}).
```

…into…

```erlang
-dialyzer({nowarn_function, {data_encode, 1}}).
```

…which is not incorrect. But it's uglier.

**Comment by paulo-ferraz-oliveira** [comment]
Ah, then you'll probably agree with my preference on https://github.com/AdRoll/rebar3_format/issues/158.
