### ISSUE TITLE
Indent one-claused anonymous functions less severely

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#142]
Currently, the default formatter indents…

```erlang
fun() -> something end,
```

…as…

```erlang
        fun () ->
                something
        end,
```

…which puts the function body actually 8-spaces into the `fun` moving code in high order functions like `lists:map/2` and others way too much to the right. The indentation is necessary for things like…

```erlang
        fun (one) ->
                the_one;
            (two) ->
                the_two
        end,
```

…but we could make one-clause anonymous functions a special case and indent them less heavily…

```erlang
        fun () ->
            something
        end,
```

**Comment by Chlorophytus** [comment]
I'll probably get to this in a bit (added a bit of tracing for certain code points of interest). The default formatter is kind of undocumented, so I am a tiny bit confused about where to proceed.

https://github.com/Chlorophytus/rebar3_format/tree/one-claused-anon-funs

**Comment by elbrujohalcon** [comment]
Yeah... The lack of documentation is real. It comes from the fact that the default formatter was originally copied from the otp formatter, in time copied from OTP's erl_prettypr...
Anyway... What I usually do in this situation is:
- add a module with sample code (in this case, anonymous functions) to `test_app/src`.
- run `rebar3 test`
- copy the formatted module from `test_app/formatted` to `test_app/after`
- *fix* the formatted module in `test_app/after` with the new expected format
- run `rebar3 test` repeatedly while adding enough `ct:pal` or `erlang:display` calls to `default_formatter` until I understand what I need to adjust (usually around `lay/2`)
- make the changes
-adjust the docs if needed
-submit a PR

TDF FTW! 💪

**Comment by elbrujohalcon** [comment]
Related to WhatsApp/erlfmt#173, by @paulo-ferraz-oliveira

**Comment by paulo-ferraz-oliveira** [comment]
I like the initial suggestion about the "one clause `if`s", indentation-wise. The formatter also apparently adds the white space after `fun` that I talked about in the related issue. That's a nice touch. (sorry, @elbrujohalcon, I know I owe you running `rebar3_format` all over the code, but I somehow got "sucked" into trying `erlfmt` by an issue on OTP's repo - I'll get there 😄).

**Comment by elbrujohalcon** [comment]
Sorry, @Chlorophytus … I completely forgot about your comment here… 🤦 
My bad… Please feel free to pick up any of the other tickets from https://github.com/AdRoll/rebar3_format/milestone/13, if you still feel like contributing 😓

**Comment by paulo-ferraz-oliveira** [comment]
I'm still getting this for e.g.
```erlang
        spawn(
            fun() ->
                {ok, _} = a:b(A, B, C),
                receive
                    go_away -> ok
                end
            end
        ),
```
(formatted as)
```erlang
        spawn(fun () ->
                      {ok, _} = a:b(A, B, C),
                      receive
                          go_away ->
                              ok
                      end
              end),
```

Is this a different issue?
[only thing wrong, in this case, for me, is the extra 4 spaces. Everything else is perfect!]

**Comment by elbrujohalcon** [comment]
You're getting this because the PR with the fix is not yet merged into the latest release.

**Comment by elbrujohalcon** [comment]
Even more, you have to wait until #156 is merged and released to see the changes in full effect.

**Comment by paulo-ferraz-oliveira** [comment]
> You're getting this because the PR with the fix is not yet merged into the latest release.

I get the same stuff and it's now merged to `master`, right? And I'm pulling from master. Unless it hasn't made its way to Hex yet.

**Comment by elbrujohalcon** [comment]
Have you upgraded your plugins? What does `rebar3 plugin list` say?
You should see something like…

```bash
--- Global plugins ---
…

--- Local plugins ---
…
rebar3_format (0.5.0)
```

**Comment by elbrujohalcon** [comment]
The code above, when I apply the formatter, looks like this:

```erlang
    spawn(fun() ->
             {ok, _} = a:b(A, B, C),
             receive go_away -> ok end
          end),
```

**Comment by paulo-ferraz-oliveira** [comment]
> Have you upgraded your plugins? What does `rebar3 plugin list` say?
> You should see something like…
> 
> ```shell
> --- Global plugins ---
> …
> 
> --- Local plugins ---
> …
> rebar3_format (0.5.0)
> ```

That might just be it. I keep forgetting `rebar3` doesn't do it by default, for plugins 👍. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
```
✗ rebar3 plugins upgrade rebar3_format
===> No upgrade needed for rebar3_format
✗ rebar3 plugins list                 
--- Local plugins ---
rebar3_format (0.4.1)
```

I think I'll "upgrade it by hand" (good'ol `rm -rf`). 🤷‍♂️

**Comment by paulo-ferraz-oliveira** [comment]
Small detail...

```erlang
    spawn(fun() ->
             {ok, _} = a:b(A, B, C),
             receive go_away -> ok end
          end),
```

There's 3-space indentation below `fun` if you start counting from `f`. Is this the expected behavior?

**Comment by elbrujohalcon** [comment]
Yeah, that's how `prettypr` works, sadly.

**Comment by paulo-ferraz-oliveira** [comment]
How does it calculate it, then?
And would changing it - to 4 - affect a whole lot of other things?

**Comment by elbrujohalcon** [comment]
It _is_ `4` already.
In this case, what `prettypr` is doing is aligning the fun body with the start of the clause (i.e. with `(` in `() ->`) without indentation, because the clause (starting with `() ->` and finishing in the first `end`) is a document on its own.
