### ISSUE TITLE
Prevent right part of a multiline assignation to go in a second line in certain conditions

### ISSUE THREAD

**Issue by ElFantasma** [AdRoll/rebar3_format#143]
Eg.
```erlang
    Variable =
        case some:function(Param) of
            value ->
                something();
            other_value ->
                something_else()
        end,
```
could go 
```erlang
    Variable = case some:function(Param) of
            value ->
                something();
            other_value ->
                something_else()
        end,
```

Another example:

```erlang
    T =
        fun (Attr, AnotherAttr) ->
                something()...
```
could be 

```erlang
    T = fun (Attr, AnotherAttr) ->
                something()...
```

This isn't so easy, as sometimes the expression on the left of `=` is long (or complex) enough to have it's own line. Like

```erlang
    {SomeLongVariableName, AnotherLongVariable} =
        case some:function(Param) of
            value ->
                ...
```
where it makes sense to let the `case` clause have it's own line.

Probably we should consider the size of the expression on the left of `=`, or maybe the horizontal placing of the `=`. Ie. force a new line if the `=` is placed further than N spaces from left margin.

**Comment by elbrujohalcon** [comment]
@david-kubecka had a similar request on WhatsApp/erlfmt#164

**Comment by elbrujohalcon** [comment]
Also related to this are #75 and #126

**Comment by elbrujohalcon** [comment]
After a long round of analysis with @ElFantasma we reached the conclusion that there is no intuitive and generic-enough algorithm to apply in the `default_formatter` to balance the needs of #75 and this ticket together. Therefore, since #75 takes precedence (i.e. that code is far uglier), we'll close this one.

**Comment by paulo-ferraz-oliveira** [comment]
Do you think it would be possible to have an option to "always force the case clause on a new line"? That's what I encourage, internally, and what I believe improves readability.

**Comment by elbrujohalcon** [comment]
I'm not sure I understand… you mean "if the right side of a match expression is a case statement, then it *must* be nested"? or you mean "anywhere in the code where a case statement appears, it should go in the next line"?
None of those seem very reasonable to me. Both of them should probably consider other expressions, like `try`, `if`, etc… and what about `case` statements within a list that's itself within a tuple?
I prefer to let `prettypr` deal with moving documents to different lines as much as I can.

**Comment by paulo-ferraz-oliveira** [comment]
I meant formatting like ("force the case clause on a new line")
```erlang
case some:function(Param) of
    value ->
        something();
    other_value ->
        something_else()
end
```
as opposed
```erlang
case some:function(Param) of
    value -> something();
    other_value -> something_else()
end,
```

---

I've also seen code written as follows, but don't often use it:
```erlang
case some:function(Param) of
    value -> something()
  ; other_value -> something_else()
end,
```

In the case of `if` it is more interesting, I think
```erlang
if A > B -> a_is_bigger
 ; A < B -> b_is_bigger
 ; _Otherwise -> 'can_you_guess?'
end,
```

**Comment by elbrujohalcon** [comment]
That's already done through `inline_clause_bodies`. If that option is `true`, the code will be formatted just the way you wanted, I believe.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, right. I though I'd read "all" the options, but I must've skipped this one. Thanks.
