### ISSUE TITLE
Spacing around parentheses / curly-braces

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#148]
Currently, `default_formatter` formats this code…

```erlang
binary_to_number( Bin ) ->
    string_to_number( binary_to_list( Bin ) ).
```

…like this…

```erlang
binary_to_number(Bin) ->
    string_to_number(binary_to_list(Bin)).
```

I would like it to have an option to format it like this…

```erlang
binary_to_number( Bin ) ->
    string_to_number( binary_to_list( Bin ) ).
```

This comes from Whatsapp/erlfmt#147, by @david-kubecka

**Comment by elbrujohalcon** [comment]
Also related to WhatsApp/erlfmt#171 (by @paulo-ferraz-oliveira), although that one is about curly braces.

**Comment by paulo-ferraz-oliveira** [comment]
> Also related to [WhatsApp/erlfmt#171](https://github.com/WhatsApp/erlfmt/issues/171) (by @paulo-ferraz-oliveira), although that one is about curly braces.

My needs are more generic than curly braces, though. I will probably have to adapt to no-spaces for maps' curly braces, but I do prefer the no-spaces approach more often than not.

**Comment by paulo-ferraz-oliveira** [comment]
If possible I'd like options for:
* spaces in maps (before `}` and after `{`),
* spaces in tuples (before `}` and after `{`),
* spaces in records (before `}` and after `{`).

**Comment by paulo-ferraz-oliveira** [comment]
Probably related (let me know if I should create a separate issue)...

```erlang
    #{
        id => counter,
        start => {?MODULE, start_link, []},
        restart => temporary,
        shutdown => 5000,
        type => worker,
        modules => [?MODULE]
    }.
```
gets formatted as
```erlang
    #{id => counter,
      start => {?MODULE, start_link, []},
      restart => temporary,
      shutdown => 5000,
      type => worker,
      modules => [?MODULE]}.
```
but I do like my spaces like so
```erlang
    #{ id => counter,
       start => {?MODULE, start_link, []},
       restart => temporary,
       shutdown => 5000,
       type => worker,
       modules => [?MODULE] }.
```
