### ISSUE TITLE
Long specs with when

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#150]
Currently, `default_formatter` formats this code…

```erlang
-spec handle_call(term(), {pid(), reference()}, state())
        -> {reply, Reply, state()} |
           {stop, unexpected_call, state()}
    when Reply :: ok | {error, {already_registered, pid()}}.
```

…like this…

```erlang
-spec handle_call(term(), {pid(), reference()}, state()) ->
                     {reply, Reply, state()} | {stop, unexpected_call, state()} when Reply :: ok |
                                                                                              {error,
                                                                                               {already_registered,
                                                                                                pid()}}.
```

I would like it to be formatted like this…

```erlang
-spec handle_call(term(), {pid(), reference()}, state()) ->
                     {reply, Reply, state()} | {stop, unexpected_call, state()}
    when Reply :: ok | {error, {already_registered, pid()}}.
```

Related to WhatsApp/erlfmt#170

**Comment by paulo-ferraz-oliveira** [comment]
Do you imagine this will be possible?
```erlang
-spec metric(Name, Value, Type) -> Result
    when Name :: binary(),
         Value :: value(),
         Type :: metric_type(),
         Result :: ok.
```

**Comment by paulo-ferraz-oliveira** [comment]
Also
```erlang
-spec gauge(Name, Value, Tags)
      -> Result
```
doesn't get formatted as
```erlang
-spec gauge(Name, Value, Tags) -> Result
```

Should this be a separate issue?

**My preference**: as much as possible declare `-spec(_).`s as shown above (inlined before the `when` with the `->` in the same line, if fitting.

**Comment by paulo-ferraz-oliveira** [comment]
Stuff's also getting transformed from 
```erlang
-spec send(Name :: binary(), Value :: binary(), Type :: type(),
           Tags :: [bin_kv()])
    -> ok.
```
to 
```erlang
-spec send(Name :: binary(),
           Value :: binary(),
           Type :: metric_type(),
           Tags :: [bin_kv()]) ->
              ok.
```

**My preference**: I like my `->` next to my result.

**Comment by elbrujohalcon** [comment]
> Do you imagine this will be possible?
> 
> ```erlang
> -spec metric(Name, Value, Type) -> Result
>     when Name :: binary(),
>          Value :: value(),
>          Type :: metric_type(),
>          Result :: ok.
> ```

That's what will likely happen if the list of types is long enough.

**Comment by elbrujohalcon** [comment]
> ```erlang
> -spec gauge(Name, Value, Tags)
>       -> Result
> ```

It does get formatted as `-spec gauge(Name, Value, Tags) -> Result.` as soon as you add the period to the right of `Result` ;)

**Comment by elbrujohalcon** [comment]
> Stuff's also getting transformed from
> 
> ```erlang
> -spec send(Name :: binary(), Value :: binary(), Type :: type(),
>            Tags :: [bin_kv()])
>     -> ok.
> ```
> 
> to
> 
> ```erlang
> -spec send(Name :: binary(),
>            Value :: binary(),
>            Type :: metric_type(),
>            Tags :: [bin_kv()]) ->
>               ok.
> ```
> 
> **My preference**: I like my `->` next to my result.

This is not impossible to change, but it's very very very unlikely since the code that formats spec "heads" is the generic code that also formats function heads, and anonymous function heads, etc… And in those scenarios you'll probably agree that having `->` right after `)` is better.

**Comment by paulo-ferraz-oliveira** [comment]
> > ```erlang
> > -spec gauge(Name, Value, Tags)
> >       -> Result
> > ```
> 
> It does get formatted as `-spec gauge(Name, Value, Tags) -> Result.` as soon as you add the period to the right of `Result` 😏

Yeah, but then it's not a _valid_ spec, since I need my types.

**Comment by paulo-ferraz-oliveira** [comment]
> And in those scenarios you'll probably agree that having -> right after ) is better.

I do agree.

I like stuff inlined after `-spec` (when using `when` -like syntax) and `when` to group stuff. But I do understand (**now**) that it's related to the way functions are formatted, so there are limitations to options.
