### ISSUE TITLE
ignore_xref's content style

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#158]
```erlang
-ignore_xref(metric/4).
```
[this is supported `rebar3 xref` syntax] gets formatted to
```erlang
-ignore_xref({metric, 4}).
```
but I actually prefer the former since I can easily copy-paste a block in an `-export(_).` section and vertically edit it to ignore a bunch of functions at the same time.

**My preference**: the first block.

**Comment by elbrujohalcon** [comment]
This will be fixed in #155

**Comment by michalmuskala** [comment]
In general the parser supports using the `foo/X` syntax in any attribute

**Comment by elbrujohalcon** [comment]
Yeah… not `epp_dodger` nor `ktn_dodger`… they parse them as tuples. 😞

**Comment by paulo-ferraz-oliveira** [comment]
We'll fix `epp_dodger` and `ktn_dodger` 😄 then we'll all be happier.

On a serious note: I do prefer `/` and can justify it - it's immediately thought of as a `module/function` statement. Also, I discovered it, by chance, a while ago, using `rebar3 xref`.

I even [briefly mentioned this elsewhere](https://github.com/tsloughter/rebar3.org/pull/40/files#diff-f0fa350d28f70ed656c276c1937e1233R523), recently.

**Comment by paulo-ferraz-oliveira** [comment]
> This will be fixed in #155

This is still happening. #155 has been merged to `master` right?

**Comment by elbrujohalcon** [comment]
https://github.com/AdRoll/rebar3_format/issues/142#issuecomment-704753955

**Comment by elbrujohalcon** [comment]
This is how my module looks if I add your text from above…

```erlang
-ignore_xref(metric/4).
```

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, I added `{plugins, [rebar3_format]}` but it keeps fetching 0.4.1. 🤷‍♂️

**Comment by paulo-ferraz-oliveira** [comment]
Hurrah, fixed!
