### ISSUE TITLE
Style in record declaration

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#159]
Is there a way to make 
```erlang
-record(combo, {
    tags :: [bin_kv()],
    options :: options()
}).
```
not be formatted?

I'm getting
```erlang
-record(combo,
        {tags :: [bin_kv()],
         options :: options()}).
```
which I don't like as much.

**My preference**: break as in the first block.

**Comment by paulo-ferraz-oliveira** [comment]
I'm also getting
```erlang
    Combo = #combo{
        tags = CanonTags,
        options = DispatchOptions
    },
```
formatted as
```erlang
    Combo = #combo{tag = CanonTags, options = DispatchOptions},
```
(probably for the same reasons).

**Comment by paulo-ferraz-oliveira** [comment]
**Related**: https://github.com/AdRoll/rebar3_format/issues/162#issue-708548280 - the readibility part.

**Comment by elbrujohalcon** [comment]
The placement of parentheses, brackets, etc… respects OTP standards (in other words, it's the same as produced by `io:format(…)`, for instance). Nevertheless, one of our first issues was related to it: #5

It's one of those things where I'm not sure if adding an option to the `default_formatter` will be the right way to go… as opposed to creating a whole new formatter (like `rok_formatter` for comma-first).

**Comment by paulo-ferraz-oliveira** [comment]
Oh 😞... but this doesn't mean the space after `{` can't be considered, right?

If I have to go
```erlang
-record(combo,
        {tags :: [bin_kv()],
         options :: options()}).
```

I prefer to go
```erlang
-record(combo,
        { tags :: [bin_kv()],
          options :: options() }).
```

**Comment by paulo-ferraz-oliveira** [comment]
> it's the same as produced by io:format(…)

```erlang
> io:format("~p", [{1, 2, 3}]).
{1,2,3}
```
and then I have `elvis` telling me to add white space 😄. [unless you're not mentioning `io:format`generically, but only for the open/close elements]

**Comment by elbrujohalcon** [comment]
Space after `{` can be considered, yes. Placing the closing bracket in the next row… maaaaaaybe.

You got me on that one. Yeah, I was only talking about closing brackets in `io:format`, but _touchè_

**Comment by elbrujohalcon** [comment]
I renamed this issue since record usage will be fixed with `inline_fields` on #162 .

**Comment by elbrujohalcon** [comment]
We're getting closer… Since #206 , you can write…

```erlang
-format #{inline_fields => none, spaces_around_fields => true}.
-record(combo, {tags :: [bin_kv()], options :: options()}).
-type combo() :: #combo{tags :: [bin_kv()], options :: options()}.
```

…and get it formatted as…

```erlang
-format #{
            inline_fields => none,
            spaces_around_fields => true
        }.

-record(combo, {tags :: [bin_kv()], options :: options()}).

-type combo() ::
    #combo{
        tags :: [bin_kv()],
        options :: options()
    }.
```

**Comment by elbrujohalcon** [comment]
The problem with…
```erlang
-record(combo, {tags :: [bin_kv()], options :: options()}).
```
…is that, according to `erl_syntax`, this thing is…

```erlang
an attribute with two arguments
`----------´      `-----------´
     |                  |
     v                  v
-record(combo, {tags :: [bin_kv()], options :: options()}).
          ^           ^
          |           |
       ´¨¨¨¨¨`     ´¨¨¨¨¨`
       an atom and a tuple
```

and we do *not* want tuples to be affected by `spaces_around_fields`.

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira can you live with the current state of the formatter? i.e. can we close this ticket?

**Comment by paulo-ferraz-oliveira** [comment]
Sure. I'll probably let you know about expectations in the future, or refer to this issue and keep quiet 😄

**Comment by elbrujohalcon** [comment]
Closing this one, then.
