### ISSUE TITLE
Blank line before `export_type`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#160]
```erlang
-type value() :: binary().
-export_type([value/0]).
```
gets formatted as 
```erlang
-type value() :: binary().

-export_type([value/0]).
```
[is there a particular reasoning for this?]

**My preference**: `-export_type(_).` declaration follow either `type` or `opaque`, but with no blank line.

**Comment by elbrujohalcon** [comment]
Yeah… `default_formatter` groups attributes by name 🤷‍♂️  since #30.
Not likely to change and even less for a very specific scenario like this one.

**Comment by paulo-ferraz-oliveira** [comment]
Fair enough.

We have to adapt, sometimes: always outnumbered, never outgunned 😄.

Maybe I'll start using `-export_type` next to `-export` and check the tool's behavior then.

Thanks.
