### ISSUE TITLE
Formatting multiline maps

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#162]
```erlang
    Options = #{
        A => 1.0,
        B => all,
        C => <<"this.that.">>
    },
```
gets formatted as
```erlang
    Options = #{A => 1.0, B => all, C => <<"this.that.">>},
```
but I actually think the former is more readable (each line is a key; think JSON).

**My preference**: increase map readability by having one key per line (even if the whole declaration fits a single line).

(I guess the same reasoning could be applied to proplists (though probably harder to detect) and might be related to the way we _see_ lists.

**Comment by elbrujohalcon** [comment]
If I get it right, you want `inline_items = none` to _force_ non-inlining even if it fits in one line, but only for certain types of items, like map or record fields.
Am I right?

Maybe something like `inline_fields => all | none` that works for records and maps… 🤔

**Comment by paulo-ferraz-oliveira** [comment]
> If I get it right, you want inline_items = none to force non-inlining even if it fits in one line, but only for certain types of items, like map or record fields.
> Am I right?

Yes, if it's possible to separate between item types, sure. I'm thinking maps, records, tuples, lists.

And yes to `force`, also. I see your decision is "inline if possible even if `none`", but I'm suggesting you to consider "forced" formatting.
