### ISSUE TITLE
case...of

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#163]
I'm getting the `of` in a new line, from
```erlang
    case whereis(ServerAndTable) =/= undefined orelse % don't mind the orelse...
             counter_sup:start_child([ServerAndTable, Name]) of
        true ->
```
to (formatted as)
```erlang
    case whereis(ServerAndTable) =/= undefined orelse % don't mind the orelse...
             counter_sup:start_child([ServerAndTable, Name])
        of
        true ->
```

**My preference**: the `of` should follow the last element before it (and not be placed in a newline).

**Comment by elbrujohalcon** [comment]
We took the inspiration from @erlang's `erl_prettypr` (which is `otp_formatter` here).
We could make the change if there are enough people interested in it, but I (for one) like the `of` in the next row. Let's see if you get traction, @paulo-ferraz-oliveira.
This will certainly not become an option, that's for sure. It either goes into the `default_formatter` or it doesn't.

**Comment by elbrujohalcon** [comment]
Just checked one thing… The default formatter produces this code:

```erlang
c() ->
    case whereis(ServerAndTable) =/= undefined
             orelse % don't mind the orelse...
             counter_sup:start_child([ServerAndTable, Name])
        of
        thing ->
            thong
    end.

t() ->
    try whereis(ServerAndTable) =/= undefined
            orelse % don't mind the orelse...
            counter_sup:start_child([ServerAndTable, Name])
    of
        thing ->
            thong
    catch
        _:_ ->
            thung
    end.
```

I really like how the `of` is placed in the `try` statement. I would like the `case` statement to be formatted in the same way.

**Comment by paulo-ferraz-oliveira** [comment]
Did it change further to approach the `try` format?

I guess it's OK, but this is a huge change for most projects.

And if they're different (as they were), would it be possible one was an option (eg `{case_of_indent, 4}`?

**Comment by paulo-ferraz-oliveira** [comment]
Nevermind. I guess it was "fixed" in a way. Still would like to know your opinion on the option.

**Comment by elbrujohalcon** [comment]
I wouldn't add an option just for that very particular and generally uncommon scenario (i.e. `case` statements with large expressions that require indentation).
Besides... @juanbono, @diegomanuel, @facundoolano and the other maintainers agree that making this compatible with the similar `try` statements is the right way to go.

**Comment by paulo-ferraz-oliveira** [comment]
Just to understand properly - sorry about insisting, (since I don't get the _very particular and generally uncommon scenario_ bit)...

1. do you think it's more frequent to have `of` in the next line, in a `case` statement?
2. can the indentation be controlled with `break_indent`? Or would this make it inconsistent with other options, since you're forcing 0-spaces-above-case?

I also believe consistency is important, by the way, but I'm curious as to what motivated the change.

**Comment by paulo-ferraz-oliveira** [comment]
For instance (and I don't want to make OTP into a "standard code base for formatting option decisions"):
1. there's very few `of` statements in a single line (less than 20),
2. there's thousand of `of` statements following the `case` header.

**Comment by elbrujohalcon** [comment]
Let's see if I can make myself clear... The change in this PR only affects case statements where the conditional expression is too long to fit in the same line as the `case` keyword. That, in my experience, is not as usual as having case statements where the conditional expression does fit.

If the condition fits in one line, `of` is kept to the right of it.
If the condition doesn't fit, then `of` is placed in the next line and aligned with `case` and `end`, just like what we do with `try...of` statements...

**Comment by paulo-ferraz-oliveira** [comment]
You've made yourself clearer. And I like the proposal for change.

**Comment by paulo-ferraz-oliveira** [comment]
The line after `orelse` is getting indented by 9 spaces. This is `case + _white_ + 4`.

Would you consider indenting it by e.g. a multiple of 4 (I found this is spec and callback, today, also, in a different issue)? 

When writing code (and people will eventually get used to the formatter's way) you tab+tab after a case (especially if your "IDE" doesn't help) and 9 spaces can't possible mean 2-tabs 😄

**Comment by paulo-ferraz-oliveira** [comment]
e.g.
```
filter_g_value_for_os_type({unix, OSName})
    when OSName =:= freebsd orelse OSName =:= linux orelse OSName =:= sunos ->
```
(this is formatted code, indented by _4-space_)

**Comment by elbrujohalcon** [comment]
> The line after `orelse` is getting indented by 9 spaces. This is `case + _white_ + 4`.
> 
> Would you consider indenting it by e.g. a multiple of 4 (I found this is spec and callback, today, also, in a different issue)?
> 
> When writing code (and people will eventually get used to the formatter's way) you tab+tab after a case (especially if your "IDE" doesn't help) and 9 spaces can't possible mean 2-tabs 😄

Well… according to `prettypr`, it's indented only `4` spaces in relation to the beginning of its containing _document_. That document being…

```erlang
whereis(ServerAndTable) =/= undefined orelse
    counter_sup:start_child([ServerAndTable, Name])
```

The fact that such a document starts in column `5` because it's placed after `case ` is _incidental_.
