### ISSUE TITLE
Unexpected blank line after %% @private

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#165]
I usually write my `edoc` related "tag" like so
```erlang
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
%% @private
resolve(Module, Host) ->
    Module:resolve(Host).
```
This is getting formatted to
```erlang
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
%% @private

resolve(Module, Host) ->
    Module:resolve(Host).
```

Is seems like a bug, but I'm not sure.

**Comment by elbrujohalcon** [comment]
Definitely a bug.

**Comment by elbrujohalcon** [comment]
Although… Why do you put your edoc comments _after_ the `spec`… WHY???? :trollface:

**Comment by paulo-ferraz-oliveira** [comment]
> WHY????
 
I imagined that, some years after starting to write Erlang, I'd come across a formatting tool whose developers I **really** wanted to annoy 😄.

On a serious note, I'll try to find a reference as to why I started doing this. I didn't start this by myself; I remember I saw it somewhere.

**Comment by paulo-ferraz-oliveira** [comment]
If it's of any consolation, `erlfmt` suffered from [a similar bug](https://github.com/WhatsApp/erlfmt/issues/176#issue-705963043). 😄

**Comment by elbrujohalcon** [comment]
Yeah, I **know**.

**Comment by paulo-ferraz-oliveira** [comment]
Another example found in the wild: https://github.com/g-andrade/aequitas/blob/master/src/aequitas_category.erl#L176.

**Comment by paulo-ferraz-oliveira** [comment]
But my source was most surely something more widely used [like lager](https://github.com/erlang-lager/lager/blob/master/src/lager_common_test_backend.erl#L55).

**Comment by elbrujohalcon** [comment]
Oh, man! Specs with _parentheses_!! 🙈

**Comment by paulo-ferraz-oliveira** [comment]
😄 long live diversity...

What about specs [as comments](https://github.com/erlang/otp/blob/master/lib/common_test/test/erl2html2_SUITE.erl#L40)?

I'm sure you're not surprised; you've seen much more that I have while working on the tool, for sure...

**Comment by paulo-ferraz-oliveira** [comment]
In any case, I wouldn't mind (let me know if I should open a new issue) that the tool moved comments from "between the spec and the function" to "above the spec", like so...

This 

```erlang
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
%% @private
resolve(Module, Host) ->
    Module:resolve(Host).
```

would become

```erlang
%% @private
-spec resolve(Module :: module(), Host :: dispatcher:host()) ->
                 {ok, [inet:ip_address()]}.
resolve(Module, Host) ->
    Module:resolve(Host).
```

**Comment by elbrujohalcon** [comment]
> 😄 long live diversity...
> 
> What about specs [as comments](https://github.com/erlang/otp/blob/master/lib/common_test/test/erl2html2_SUITE.erl#L40)?
> 
> I'm sure you're not surprised; you've seen much more that I have while working on the tool, for sure...

Yeah… that's ye ould edoc style…

**Comment by elbrujohalcon** [comment]
> In any case, I wouldn't mind (let me know if I should open a new issue) that the tool moved comments from "between the spec and the function" to "above the spec", like so...
> 
> This
> 
> ```erlang
> -spec resolve(Module :: module(), Host :: dispatcher:host()) ->
>                  {ok, [inet:ip_address()]}.
> %% @private
> resolve(Module, Host) ->
>     Module:resolve(Host).
> ```
> 
> would become
> 
> ```erlang
> %% @private
> -spec resolve(Module :: module(), Host :: dispatcher:host()) ->
>                  {ok, [inet:ip_address()]}.
> resolve(Module, Host) ->
>     Module:resolve(Host).
> ```

This will be super nice, but I don't know if it's possible at all, without breaking other things.

**Comment by elbrujohalcon** [comment]
@paulo-ferraz-oliveira can you confirm if this is still happening?
I just tried to format the following module and there was no new line introduced after the comment.

```erlang
-module(a_module).

-spec resolve(Module :: module(), Host :: dispatcher:host()) -> {ok, [inet:ip_address()]}.
%% @private
resolve(Module, Host) ->
    Module:resolve(Host).
```

**Comment by paulo-ferraz-oliveira** [comment]
This seems to have gone away. At least in `master`.

**Comment by elbrujohalcon** [comment]
Thanks.
