### ISSUE TITLE
Recover sub_indent and use it to indent `when` in function declaration

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#166]
I'm getting stuff formatted as 
```erlang
handle_call({update, NewValue, NewOptions}, {FromPid, _CallRef}, State)
    when FromPid =:= State#state.owner_pid ->
    UpdatedState = State#state{
```
do you thing further indent `when` by 4 spaces would improve readability, as we would easily distinguish it from the function body?

**My preference**: if it fits in the same line, leave it there; otherwise indent it by 8 spaces, not 4.

**Comment by elbrujohalcon** [comment]
Originally, both the `default_formatter` and the `otp_formatter` (based on `erl_prettypr`, by @erlang) had a `sub_indent` parameter used for this scenario. That would've indented `when` to whatever `sub_indent` value you wanted (`2` was the default).
They removed it in OTP23. When they removed it from their formatter, we removed it from ours ( #134 , #130 ). We might want to recover it, but defaulting to the value of `break_indent`.

**Comment by paulo-ferraz-oliveira** [comment]
I'm _not worried_ about the `default_formatter`. It's very possible I'll simply use a configured version (on top the defaults, that is), but I _am_ worried about having choices 😄. Again, thanks for considering this.

**Comment by elbrujohalcon** [comment]
The `default_formatter` *is* the one with the options.

**Comment by paulo-ferraz-oliveira** [comment]
Ha. 😄 Long story short: gimme them options.
