### ISSUE TITLE
`of` in `case` doesn't get formatted to next line

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#186]
I'm getting 
```erlang
    {DoSend, SampleRate}
        = case SampleRate0 < 1.0 of
              true ->
```
formatted as
```erlang
    {DoSend, SampleRate} =
        case SampleRate0 < 1.0 of
            true ->
```
which is not "wrong".

I'm just wondering what's the rule for the `of` to show in the next line. Does it have to do with `ribbon`/`paper`? Or should it always go there?

**Comment by paulo-ferraz-oliveira** [comment]
Another example
```erlang
    Fun
        = case Item of
              {Fun0, tag} -> Fun0;
              Fun0 -> Fun0
```
gets formatted to
```erlang
    Fun = case Item of
              {Fun0, tag} ->
                  Fun0;
              Fun0 ->
                  Fun0
```

**Comment by elbrujohalcon** [comment]
Yeah, that's _by design_.
Do you really want `of` in the next line in those examples?

> I'm just wondering what's the rule for the `of` to show in the next line. Does it have to do with `ribbon`/`paper`? Or should it always go there?

Yeah, it only goes in the next line when needed.

**Comment by paulo-ferraz-oliveira** [comment]
> Do you really want of in the next line in those examples?

No, but I want to understand why...

> it only goes in the next line when needed (i.e. when the conditional expression spans multiple lines)

And now I know 😄 

Thanks.
