### ISSUE TITLE
Keep extra space after `fun`, for anonymous functions

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#187]
Currently, `default_formatter` formats this code…

```erlang
    lists:filter(fun ({TagKey, _TagValue}) ->
```

…like this…

```erlang
    lists:filter(fun({TagKey, _TagValue}) ->
```

I would like it to be formatted like this…

```erlang
    lists:filter(fun ({TagKey, _TagValue}) ->
```
(as was, so it's easier to see it's an anonymous `fun`).

If this has been decided upon earlier, though, I retract my suggestion.

**Comment by elbrujohalcon** [comment]
I'll leave this open for voting, but yeah… we moved it to `fun(…)` explicitly, and adding an option just for this extra space doesn't seem worth it to me.

**Comment by paulo-ferraz-oliveira** [comment]
I'm not suggesting an option. I'm suggesting a change. 😄 If y'all decide to keep it as-is it's not the worst thing that's happened.

**Comment by elbrujohalcon** [comment]
It was explicitly changed to be like this, so… yeah. Our opinion (as NextRoll) is that it should be `fun(`, particularly because we have way to many `fun() -> …`'s
