### ISSUE TITLE
parenthesize_infix_operations' aggressiveness

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#191]
This is more of a question (I don't know if a bug, or a suggestion).

It seems `parenthesize_infix_operations => true` is formatting
```erlang
    list_to_binary(atom_to_list(StatsInfoContainer) ++ "_" ++ atom_to_list(Item)).
```
as
```erlang
    list_to_binary(atom_to_list(StatsInfoContainer) ++ ("_" ++ atom_to_list(Item))).
```
(too aggressive a format?)

If:
1. it's expected, we can close the issue,
2. it's a bug, we should move it to "bug",
3. it's none of the previous, it's a suggestion for improvement.

**Comment by elbrujohalcon** [comment]
It's expected. It is _precisely_ the idea and the level of aggressivity is exactly the reason why the default is `false`.

**Comment by elbrujohalcon** [comment]
To see where this can be useful try using `--` twice... ;)
