### ISSUE TITLE
Accept concatenated record access

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#198]
Currently, `default_formatter` formats this code…

```erlang
a_record#a_field#another_record.another_field
```

…like this…

```erlang
(a_record#a_field)#another_record.another_field
```

I would like it to be formatted like this…

```erlang
a_record#a_field#another_record.another_field
```

**Comment by paulo-ferraz-oliveira** [comment]
Do you think it would make sense to have something like `parenthesize_infix_operations` for these cases? I see parenthesis as increasing readability.

**Comment by elbrujohalcon** [comment]
You've got to be kidding me!

I got to tell you that this hits a personal nerve… since I was one of those who vocally advocated for this syntax to be valid several years ago.

If you find more people that see this as you do, @paulo-ferraz-oliveira … I would gladly accept a PR. :trollface:

**Comment by paulo-ferraz-oliveira** [comment]
I didn't mean to upset anybody. I now retract my suggestion, as indeed it seems silly.
