### ISSUE TITLE
Modules called ignore are incorrectly formatted

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#247]
### Describe the bug
Parentheses are removed when formatting a module called `ignore`.

### To Reproduce
Try to format this…

```erlang
-module(ignore).
```

It's formatted as…

```erlang
-module ignore.
```

### Expected behavior
```erlang
-module(ignore).
```

**Comment by paulo-ferraz-oliveira** [comment]
It's an easter egg.

**Comment by elbrujohalcon** [comment]
# 🥚

**Comment by paulo-ferraz-oliveira** [comment]
On a more serious note I find that not being able to express `ignore => [atom()]`, in the options, is hindering. I had to do "`src/module.erl`" (didn't check without the `src`).

**Comment by elbrujohalcon** [comment]
You mean in `rebar.config`'s `format` section, right?

**Comment by paulo-ferraz-oliveira** [comment]
Yes.

**Comment by elbrujohalcon** [comment]
☝️ #248

**Comment by elbrujohalcon** [comment]
Fixed with #253
