### ISSUE TITLE
Default configuration doesn't format rebar.config

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#251]
**Describe the bug**
Without specifying any configuration in `rebar.config`, the file `rebar.config` (and any other config file in the root directory, like `elvis.config`) is not formatted.

**To Reproduce**
Just add the plugin to a project and run `rebar3 format`

**Expected behavior**
All config files in the root folder to be formatted.

**Comment by vkatsuba** [comment]
@elbrujohalcon I was play with CT and was detected that all is working as expected, was also added `rebar3_format` to real project and latest version do formatting of `*.config` files as expected. However I was see that the test case for `*.config` was missed, so was added this small changes. Perhaps you did not close the config file in some editor when starting the plugin, in my editor the file was not formatted at the time of using the editor, but if I close file in the editor, then run the plugin and reopen the config file - everything is formatted by default.

Regards,
--V

**Comment by elbrujohalcon** [comment]
Yeah. That might have been the case. Thanks for the investigation, @vkatsuba !!

**Comment by elbrujohalcon** [comment]
Fixed by #254
