### ISSUE TITLE
Option to indent/inline all clauses consistently

### ISSUE THREAD

**Issue by facundoolano** [AdRoll/rebar3_format#51]
Add an option to either indent all or inline all clauses, when at least one needs indentation, i.e. no:

```erl
             case lists:keyfind(From, 1, Plist) of
               {From, Value} ->
                   %% we found an entry for the From key, so dupe it
                   %% to the To key:
                   [{To, Value} | Plist];
               false -> Plist
             end
```

**Comment by pbrudnick** [comment]
Should it be optional? 
If the community tend to use this formatter, would we expect the "same" format in all the projects? (like the elixir one https://hexdocs.pm/mix/master/Mix.Tasks.Format.html)

**Comment by elbrujohalcon** [comment]
@pbrudnick well… there is a long discussion about this, i.e. how opinionated this formatter should be. I think that's the trickiest part of this whole thing.
