### ISSUE TITLE
We removed too many parentheses

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#74]
The formatter currently formats…

```erlang
-define(Now(), 100).
-define(Elapsed(Since), (?Now() - Since)).
-define(Remains(Since, Remaining), N - ?Elapsed(Since)).
```

…as…

```erlang
-define(Now(), 100).
-define(Elapsed(Since), ?Now() - Since).
-define(Remains(Since, N), N - ?Elapsed(Since)).
```

…which is, of course, wrong.

The result of `?Remains(1, 200)` should be `200 - (100 - 1) = 101` and not `200 - 100 - 1 = 99`.

**Comment by elbrujohalcon** [comment]
This issue can't be solved until we have a fix for inaka/katana-code#40.

**Comment by michalmuskala** [comment]
This is also problematic with parentheses used in macro calls. Does rebar3_format preserve them now?

e.g.
```
-define(MUL(A, B), A * B).

?MUL((1 + 2), (3 + 4)).
```
With parens in the call it's 21, without it's 11

**Comment by elbrujohalcon** [comment]
Good catch, @michalmuskala! 

And… of course `rebar3_format` doesn't preserve them… 🤦

**Comment by elbrujohalcon** [comment]
Man… I hate macros so much!
To be fair… I hated them way before working on the formatter… even before working on a linter…

![old man yells at cloud](https://static.wikia.nocookie.net/memepediadankmemes/images/0/01/297.jpg/revision/latest?cb=20180908193511)
