### ISSUE TITLE
Parser tries to format .xrl file

### ISSUE THREAD

**Issue by hengestone** [AdRoll/rebar3_format#78]
Thanks for working on the formatter, it's a big timesaver!

Ran into this today:
`
===> Formatting "src/xdr_lexer.xrl" with #{output_dir => "formatted/"}
===> Couldn't parse src/xdr_lexer.xrl: ["syntax error before: ",
                                               "Definitions"]
`

The file source is at https://github.com/seniverse/xdrc/blob/master/src/xdr_lexer.xrl

Maybe filter out any files that are not `.hrl`/`.erl` ?

**Comment by gilbertwong96** [comment]
This format plugin cannot format rebar.config for now.

**Comment by elbrujohalcon** [comment]
> This format plugin cannot format rebar.config for now.

It's not as easy as it sounds, but feel free to open a ticket for that and we'll work on it eventually.
