### ISSUE TITLE
Redundant trailing newline added

### ISSUE THREAD

**Issue by puzza007** [AdRoll/rebar3_format#82]
When run on https://github.com/puzza007/katipo/ all files have a trailing newline added. A newline on the last non-empty line should be enough (https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206).

```diff
diff --git a/src/katipo_pool.erl b/src/katipo_pool.erl
index 216c58a..d6aa69e 100644
--- a/src/katipo_pool.erl
+++ b/src/katipo_pool.erl
@@ -5,25 +5,22 @@
 -export([stop/1]).

 -type name() :: atom().
+
 -export_type([name/0]).

 -spec start(name(), pos_integer()) -> supervisor:startchild_ret().
 start(PoolName, PoolSize) ->
     start(PoolName, PoolSize, []).

--spec start(name(), pos_integer(), katipo:curlmopts()) ->
-                   supervisor:startchild_ret().
+-spec start(name(), pos_integer(), katipo:curlmopts()) -> supervisor:startchild_ret().
 start(PoolName, PoolSize, WorkerOpts)
-  when is_atom(PoolName) andalso
-       is_integer(PoolSize) andalso
-       is_list(WorkerOpts) ->
+    when is_atom(PoolName) andalso is_integer(PoolSize) andalso is_list(WorkerOpts) ->
     Args = [WorkerOpts],

-    PoolOpts = [{worker, {katipo, Args}},
-                {workers, PoolSize}],
-
+    PoolOpts = [{worker, {katipo, Args}}, {workers, PoolSize}],
     wpool:start_sup_pool(PoolName, PoolOpts).

 -spec stop(name()) -> ok.
 stop(PoolName) when is_atom(PoolName) ->
     wpool:stop_sup_pool(PoolName).
+
```

```shell
hexdump -c src/katipo_pool.erl | tail -3
00002b0   o   l   :   s   t   o   p   _   s   u   p   _   p   o   o   l
00002c0   (   P   o   o   l   N   a   m   e   )   .  \n  \n
00002cd
```

**Comment by elbrujohalcon** [comment]
FWIW, the newline was added _on purpose_ but I don't remember what the actual purpose was… maybe it's irrelevant now.
For reference: https://github.com/AdRoll/rebar3_format/blob/b75a98bbd34b23abd488a1ce546fafc4e6dadd8c/src/rebar3_formatter.erl#L88

**Comment by puzza007** [comment]
Hehe gotcha 😉  I'm not sure what others think but I kinda feel like it's superfluous.

**Comment by elbrujohalcon** [comment]
Yeah, at the very minimum it should be an option and maybe even `false` by default.

**Comment by maciej-szlosarczyk** [comment]
Hi! I looked into this briefly it seems it is more complex than adjusting the ExtandedAST. When we don't add the new line character explicitly, it results in existing new line characters being removed from the end of the file, so that the last line is not in the state we would want:

```diff
-    end.
-
+    end.
\ No newline at end of file
```

**Comment by elbrujohalcon** [comment]
So, `{eof, 0}` ends up being `\n\n`… :thinking_face:

**Comment by maciej-szlosarczyk** [comment]
AST ommits `\n` from the lines. Here's a basic example:

```erlang
%% test_module.erl
-module(test_module).

-define(CONST, value).
```

Hex:

```hex
0000000   -   m   o   d   u   l   e   (   t   e   s   t   _   m   o   d
0000010   u   l   e   )   .  \n  \n   -   d   e   f   i   n   e   (   C
0000020   O   N   S   T   ,       v   a   l   u   e   )   .  \n
000002e
```

ktn_dodger:parse_file/2 AST representation:
```erlang
{ok,[{tree,attribute,
           {attr,[{text,"module"},{location,1}],[],none},
           {attribute,{tree,atom,
                            {attr,[{text,"module"},{location,1}],[],none},
                            module},
                      [{tree,atom,
                             {attr,[{text,"module"},{location,1}],[],none},
                             test_module}]}},
     {tree,attribute,
           {attr,[{text,"define"},{location,3}],[],none},
           {attribute,{atom,[{text,"define"},{location,3}],define},
                      [{var,[{text,"CONST"},{location,3}],'CONST'},
                       {atom,[{text,"value"},{location,3}],value}]}}]}
```

Knowing that, here's how I think the new option should work:
- When there is no `\n` at the end of the file, insert it.
- When there are many `\n` at the end of the file, replace it with one.
- When there is exactly one `\n` at the end of the file, retain it.

`erl_tidy` handles it the same way as described above, so I guess that should be the default behaviour. I'll try to experiment with an implementation a little bit and open a PR when I'm ready.

**Comment by elbrujohalcon** [comment]
I agree with you @maciej-szlosarczyk. And I wouldn't bother adding an option, just make that the default behavior.

**Comment by elbrujohalcon** [comment]
Thank you @maciej-szlosarczyk !

**Comment by puzza007** [comment]
Thanks @elbrujohalcon @maciej-szlosarczyk !
