### ISSUE TITLE
Exclude certain files from formatting

### ISSUE THREAD

**Issue by michalwski** [AdRoll/rebar3_format#87]
I'm not able to use the plugin in bigger projects like [esl/MongooseIM](https://github.com/esl/MongooseIM) or [esl/escalus](https://github.com/esl/escalus) because of some files crashing the plugin. The crash is most probably due to macro expansion (which was already mentioned in issues of this project). It'd helpful to exclude some files from formatting, this is probably not possible currently with the `files` option which takes a `wildcard` to get list of files to format.

**Comment by elbrujohalcon** [comment]
We could actually do two things:
1. add a parameter to the rebar.config `format` section called `exclude` or `ignore` where you can put a list of files to ignore.
2. add a per file option like `-format #{ignore => true}.` or `-format ignore.` that marks the file itself as ignored by the formatter.

I like both ideas and I think both are relatively easy to implement.
